### ISSUE TITLE
Migrate to Node.js native test runner

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/domain-check#22]
Migrate from tape to Node.js native test runner

https://nodejs.org/api/test.html

Please remove unused dependencies (I think we can also remove cross-env).

**Comment by fabnguess** [comment]
hi @fraxken , i wanted to take this issue, but it seems to have already been dealt with [https://github.com/NodeSecure/domain-check/blob/main/test/index.js#L2](url)
