### ISSUE TITLE
Add API documentation to README

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/domain-check#23]
Hello :wave:

The goal of the task is to add API documentation to the README. Current API is a bit obscure and can be quite complicated to understand at first look.

Example of API documentation can be found in another project like [RC](https://github.com/NodeSecure/rc#api).

**Comment by manan1979** [comment]
hi @fraxken can u guide me how do i add API documentation to the readme

**Comment by fraxken** [comment]
@manan1979 It's equivalent to writing documentation, so it required to look at the code. You need to have some understading of markdown. For how to do it exactly, that's why I linked an "example" project.

Can't help that much, if you have more precise questions do not hesitate
